apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://syg-prometheus.cqewdygqded2g4gf.westeurope.azurecontainer.io:9090
    basicAuth: false
    isDefault: true
    editable: true