name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: syg-backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Build with Maven
      run: mvn clean verify
        
     # Mover el reporte de cobertura a la raíz del proyecto
    # - name: Move coverage report to project root
    #   run: |
    #      mkdir -p coverage
    #      cp -r SYG-bootstrap/target/site/jacoco-aggregate/jacoco.csv coverage/
    #      cp -r SYG-bootstrap/target/site/jacoco-aggregate/index.html coverage/

    # - name: Configurar Git para el commit
    #   run: |
    #     git config --global user.name "AlvaroGlezC"
    #     git config --global user.email "uo251891@uniovi.es"
    
    # - name: Hacer commit y push de la cobertura
    #   run: |
    #     git add -f coverage
    #     git commit -m "Agregar reporte de cobertura"
    #     git push

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: SYG-bootstrap/target/site/jacoco-aggregate/jacoco.xml
    
