name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: syg-backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Build with Maven
      run: mvn clean verify

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: SYG-bootstrap/target/site/jacoco-aggregate/jacoco.csv
        coverage-label: coverage
        
     # Mover el reporte de cobertura a la raíz del proyecto
    - name: Move coverage report to project root
      run: |
         mkdir -p coverage
         cp SYG-bootstrap/target/site/jacoco-aggregate/* coverage/
