name: Build
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: syg-backend
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
    
    - name: Build with Maven and generate JaCoCo report
      run: mvn clean verify

     # Mover el reporte de cobertura a la raíz del proyecto
    - name: Move coverage report to project root
      run: |
         mkdir -p coverage
         cp target/site/jacoco/* coverage/
